### ISSUE TITLE
Implement GalSim `Shear` object

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/JAX-GalSim#18]
This is a perfect PR to get started with contributing to the codebase, the goal is to port the galsim Shear object, defined here:
https://github.com/GalSim-developers/GalSim/blob/ece3bd32c1ae6ed771f2b489c5ab1b25729e0ea4/galsim/shear.py#L24
and which is essentially just a wrapper around a set of utility functions to convert between different definitions of shear.

This is very similar to the implementation of the `Position` object in #11 

If you decide to tackle this problem, just mention in this issue that you wish to take on this task, and have a look at the [CONTRIBUTING.md](https://github.com/GalSim-developers/JAX-GalSim/blob/main/CONTRIBUTING.md) for a primer on how to get started, and don't hesitate to use this thread for discussion if any questions arise :-)

**Comment by andyyPark** [comment]
I just found out about this project and if it's not too late, I would like to take a stab at this!
