### ISSUE TITLE
Updating the name of this package?

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/JAX-GalSim#20]
If we want to change the name of this package to something better, it's more or less now or never ^^ 

We have a poll running here: https://github.com/GalSim-developers/JAX-GalSim/discussions/2

But with very few votes. Should we try to advertise it more broadly? Should we just go ahead and rename everything to galaxim now? Or should we wait until we have more of a working minimal demo code to get people's attention?

**Comment by EiffL** [comment]
Yeahhh... Hummmm I'm wondering what is a good stage to ping the GalSim mailing list. I was initially thinking that we want to have a demo of being able to draw an image with the standard API, and jit that code...

**Comment by EiffL** [comment]
Ok, I think I'll update the name of the project to GaLAXim  if that sounds good to everybody :-) ? @ismael-mendoza @b-remy 
Let me know if you have a preference on the lower/upper case spelling ;-)

**Comment by b-remy** [comment]
GaLAXim sounds great to me! I think that sums up the purpose of the package very well.

**Comment by ismael-mendoza** [comment]
I also think that this name is good!

**Comment by ismael-mendoza** [comment]
seems like most of us are happy with `jax-galsim` as of now but we can reopen if @EiffL or anyone thinks that we should reconsider
