### ISSUE TITLE
BUG: _isPixelScale  is false while instanting a PixelScale

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/JAX-GalSim#22]
Hi, 
In the "drawing" branch of JaxGalSim there is something  strange concerning the check if the wcs of an image is a PixelScale
1) in PixelScale class (wcs.py) there is a "isPixelScale" function but no "_isPixelScale"
2) there is many "self.wcs._isPixelScale" and one "image.wcs.isPixelScale"

```
./image.py:279:        if self.wcs is not None and :
./image.py:345:        if self.wcs is not None and not self.wcs._isPixelScale:
./image.py:570:        if not self.wcs._isPixelScale:
./image.py:612:        if not self.wcs._isPixelScale:
./gsobject.py:403:        # if wcs is None or (wcs.isPixelScale and wcs.scale <= 0):
./gsobject.py:498:        if image.wcs is None or not image.wcs.isPixelScale:
./wcs.py:526:    def isPixelScale(self):
./wcs.py:800:    def isPixelScale(self):
```
now I understand that the base class in JaxGalSim/wcs.py  `BaseWCS` inherit from the GalSIm python class `_galsim.BaseWCS` which defines a default (around L1515 of GalSim/wcs.py)
```python
    @property
    def _isPixelScale(self):
        return False
```
So, contrary to the counter part PixelScale in GalSim that override this default function, in JaxGalSIm the _isPixelScale of PixelScale class is calling the GalSIm  BaseWCS::_PixelScale  which return False
```python
a_ps = galsim.PixelScale(float(0.1))
assert a_ps.isPixelScale() # True
assert isinstance(a_ps,galsim.wcs.PixelScale) # True
assert a_ps._isPixelScale  # Crash 
```
This is not that one expects and I think this is a BUG

It forbids for instance to use calculate_fft on a Image object that as wcs init via scale=...

**Comment by ismael-mendoza** [comment]
deprecated
