### ISSUE TITLE
Image array numpy->jax.numpy transform in kargs not implemented

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/JAX-GalSim#25]
Hi
In the current version if 
```python
tmp = np.array([1.,2.])
img = galsim.kImage(array=tmp)
type(img.array)
```
shows that the **numpy array has not been transformed to jnp.array.** 
Notice that
```python
img = galsim.kImage(tmp)
type(img.array)
```
does the transform.

So it is the kargs management that is not corect. A possible solution is in `image.py __init__`
```python
        else:
            if "array" in kwargs:
                array = kwargs.pop("array")

                #JEC assure that the array is a JAX array as in the "args" case
                if isinstance(array, np.ndarray):
                    array = jnp.array(array)
```

**Comment by ismael-mendoza** [comment]
I'm not sure this is a problem that we need to fix, user should use a jax array if they ended to do jitting/vmapping, etc.
