### ISSUE TITLE
Black formatting incompatible with pre-commit hook and contributing guidelines

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/JAX-GalSim#46]
@ismael-mendoza  I noticed this change in the formatting checks performed by the CI script:
https://github.com/GalSim-developers/JAX-GalSim/blob/b310313172b11ac971d82177a3915c99fcca5938/.github/workflows/python_package.yaml#L30

But this is not compatible with what is found here:
https://github.com/GalSim-developers/JAX-GalSim/blob/b310313172b11ac971d82177a3915c99fcca5938/.pre-commit-config.yaml#L5

or there:
https://github.com/GalSim-developers/JAX-GalSim/blob/b310313172b11ac971d82177a3915c99fcca5938/CONTRIBUTING.md?plain=1#L125

In general, I would advocate for not trying to modify `black` to make it look nicer, because it defeats the main purpose of `black`: stopping all arguments about the formatting of the code by removing all degrees of freedom. 

So would you be ok @ismael-mendoza with removing that argument for lines of size 100?

**Comment by ismael-mendoza** [comment]
yes I agree with this, thanks!
