### ISSUE TITLE
Work Space basket to save constant once first computed

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/JAX-GalSim#51]
This issue is to keep track of a remark done in PR #49 concerning the Moffat psf. In this class there are constants (maxK, stepK) that are computed when the function _maxk are called
```python
@property
    def _maxk(self):
     ....
```
The point is that such variable  (self._maxk) in the GalSim code is computed in the _init_ function at the construction of the object, but this is not possible to do it like that in JAX-GalSim due to jitting. 

So, what is proposed is a Work SPace mechanism in the same spirit of the use in the  JAX-Cosmo:Cosmology class. 
A discussion is also open in the JAX repo [here](https://github.com/google/jax/discussions/17268)

**Comment by beckermr** [comment]
done for gsobjects and with the lazy property decorator.
