### ISSUE TITLE
Minimal base class `GSObject` compatible with JAX tracing, and  `Sum`, `Gaussian`, `Exponentional`

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/JAX-GalSim#6]
The strategy for implementating GSObject is presented in the [design document](https://docs.google.com/document/d/1NalCc_5dc3Z8F4q37y-RsJS_mr9gzvfyANb2PYUpsb4/edit?usp=sharing) based on using PyTrees. 

This issue will track the actual implementation and can be used to discuss any issues that may come up.

**Comment by ismael-mendoza** [comment]
I agree with this, it's more stable and in addition easier to handle as a dependency since it's pinned in pypi.
