### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by ismael-mendoza** [GalSim-developers/JAX-GalSim#88]
- [x] #71 
- [x] commented out code
- [x] places where black formatting makes code particularly difficult to read (refactor into multiple lines) e.g. [here](https://github.com/GalSim-developers/JAX-GalSim/blob/4b12d6b3520938cd823ae3978c400bb9a2b454d3/jax_galsim/bessel.py#L13)
- [x] anything else that might make code difficult to read or use?

**Comment by beckermr** [comment]
Marking this as closed by #117
